spring.application.name=pet-management-system
spring.datasource.url=jdbc:mysql://localhost:3306/vetdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=8080

app.jwt-secret=daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
app.jwt-expiration-milliseconds=604800000

# Multipart file upload configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# OTP settings
app.otp.expiry-minutes=5

# Telegram bot configuration (leave empty to disable Telegram send)
telegram.bot-token=8615111673:AAE8PpI3zo91cs3KAfi0I6sr9srn_KDsWfs
telegram.chat-id=6941781695

# Medical chat upload limits
app.medical-chat.max-image-size-mb=5
app.medical-chat.max-images-per-upload=10

